version: "3"
services:
  proxy-switcher:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - "4000"
    ports:
     - "4000:4000"
    networks:
      - default
    volumes:
      - .:/home/stubz/projects
networks:
  default:
    external:
      name: shared-network
